# Generated by Django 3.0.8 on 2020-09-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='date and time of application'),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='date and time of job creation'),
        ),
    ]
