# Generated by Django 3.0.8 on 2020-09-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment', '0002_auto_20200901_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(default='500,000/=', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='vacancies',
            field=models.IntegerField(default=1),
        ),
    ]
