# Generated by Django 3.0.8 on 2020-09-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment', '0003_auto_20200901_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='vacancies',
            field=models.IntegerField(),
        ),
    ]
