# Generated by Django 3.0.8 on 2020-09-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment', '0005_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='middle_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
